### ISSUE TITLE
The package could not be installed. The theme is missing the style.css stylesheet.

### ISSUE THREAD

**Issue by gstrainovic** [nego-solutions/Bootstrap-Grid-for-SiteOrigin-Panels#4]
The package could not be installed. The theme is missing the style.css stylesheet.

**Comment by superwpheroes** [comment]
Hello!
Actually, i’m afraid this was a side project of one of our employees; it is not really supported and I don’t think it was ever conpleted :(
Not sure if AJ is following so he may help you out?

**Comment by gstrainovic** [comment]
For me it has been done, I have chosen another solution. 
The issue can be closed. 
I just wanted to point out the issue.
